title = "blog"
mode = "dev"
port = 8085
host = "0.0.0.0"

# 分页
page_min = 5
page_max = 30

# 数据库
[db]
# mysql\sqlite
type = "sqlite"
mysql = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=true&loc=Local"
sqlite = "file:goblog.db"

[orm]
# https://gitea.com/xorm/xorm
# 推荐cpu核心数
idle = 4
# 推荐cpu核心数*2
open = 8
# 显示sql
show = true 
# 同步表结构
sync = true
# 是否使用orm缓存
cache_use = false 
# orm缓存数量
cache_size = 1024
# orm劫持日志输出
hijack_log = true

# 作者
[author]
name = "lirchis"
website = "https://github.com/lirchis"

